In [2]:
import pandas as pd
df1 = pd.read_csv('orders.txt')
df1

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [26]:
df2 = pd.read_csv('returns.txt')
df2

           order_id Return_Reason
0    CA-2020-104689   Wrong Items
1    CA-2020-105081   Wrong Items
2    CA-2020-105291   Wrong Items
3    CA-2020-105585   Wrong Items
4    CA-2020-106950   Wrong Items
..              ...           ...
291  US-2021-136679        Others
292  US-2021-147886        Others
293  US-2021-147998   Wrong Items
294  US-2021-151127   Wrong Items
295  US-2021-155999   Wrong Items

[296 rows x 2 columns]

In [30]:
#1- write a program to get category wise sales of orders that were not returned
dfr=pd.merge(left = df1 , right = df2 ,how = 'left', left_on = 'order_id' , right_on = 'order_id')
fc = dfr['Return_Reason'].isna() #gives a boolean array for all the not returned orders
df1[fc].groupby('category', as_index=False)['sales'].sum()
#first did left join on 'orders' and 'returns' table on 'order_id' and then check for isnull on 'Return Reason' column and applied the filter condition 
#after applying filter condition group by category and on sum of sales

          category        sales
0        Furniture  582415.6449
1  Office Supplies  284516.2270
2       Technology  174630.6580

In [38]:
#2- write a program to get city wise count of return orders
dfr=pd.merge(left = df1 , right = df2 ,how = 'inner', left_on = 'order_id' , right_on = 'order_id')
dfr['city'].value_counts()
#above script gives citywise count of return orders and changes the index column from 'Return_Reason' to 'return_order_count'

city
Los Angeles      50
Seattle          25
San Francisco    24
New York City    11
San Diego         9
                 ..
Redmond           1
York              1
Pueblo            1
Rome              1
Pharr             1
Name: count, Length: 119, dtype: int64

In [41]:
#3- write a program to print cities where we have all 3 kinds of returns (others,bad quality,wrong items)
dfr=pd.merge(left = df1 , right = df2 ,how = 'inner', left_on = 'order_id' , right_on = 'order_id')
city_return_ucounts = dfr.groupby('city')['Return_Reason'].nunique() # Counts the uniques values of Return_Reason for each city 
city_return_ucounts[city_return_ucounts.values > 1]

city
Brentwood        2
Chicago          2
Columbia         2
Columbus         2
Concord          2
Costa Mesa       2
Denver           2
Fairfield        2
Houston          2
Jackson          2
Lakewood         2
Los Angeles      4
Lowell           2
New York City    3
Oakland          2
Pasadena         2
Rochester        2
San Diego        2
San Francisco    2
Seattle          2
Springfield      2
Name: Return_Reason, dtype: int64

In [11]:
#4- write a program to find cities where not even a single order was returned.
dfr=pd.merge(left = df1 , right = df2 ,how = 'left', left_on = 'order_id' , right_on = 'order_id')
fc = dfr['Return_Reason'].isna() #gives a boolean array for all the not returned orders
df1[fc]['city']

0       New York City
1       San Francisco
2        Jacksonville
3       New York City
4            Glendale
            ...
5004          Seattle
5005          Elkhart
5006       Providence
5007        Milwaukee
5008     Philadelphia
Name: city, Length: 4718, dtype: object

In [16]:
#5- write a program to find top 3 cities by sales
df1.groupby('city', as_index=False)['sales'].sum().sort_values(by = 'sales', ascending = False).head(3)

              city       sales
329  New York City  115073.919
266    Los Angeles   79663.299
438  San Francisco   52590.648

In [27]:
#6- write a program to get order ids whos return reason is not known (nan)
fc = df2['Return_Reason'].isnull()
df2[fc]

           order_id Return_Reason
11   CA-2020-114307           NaN
29   CA-2020-133368           NaN
107  CA-2018-105270           NaN
142  CA-2018-164721           NaN
149  CA-2019-105158           NaN

In [43]:
#7- write a program to fill unknown return reason to a default value 'others'
df2['Return_Reason'] = df2['Return_Reason'].fillna(value='others')
df2

           order_id Return_Reason
0    CA-2020-104689        others
1    CA-2020-105081        others
2    CA-2020-105291        others
3    CA-2020-105585        others
4    CA-2020-106950        others
..              ...           ...
291  US-2021-136679        others
292  US-2021-147886        others
293  US-2021-147998        others
294  US-2021-151127        others
295  US-2021-155999        others

[296 rows x 2 columns]

In [25]:
#8- write a program to find avg sales and avg profit for each category
df1.groupby('category', as_index=False).agg({'sales':'mean','profit':'mean'})

          category       sales     profit
0        Furniture  356.212758   9.813403
1  Office Supplies  107.680040  18.906134
2       Technology  382.705186  75.452770